### ISSUE TITLE
Internationalization for translated fields doesn't work

### ISSUE THREAD

**Issue by bolshakov** [unmantained-activeadmin-plugins/activeadmin-globalize#2]
``` ruby
# app/admin.project.rb
ActiveAdmin.register Project do
  form do |f|
      f.translated_inputs do |t|
         t.input :title
      end 
  end
end
```

``` yml
# config/locales/ru.yml
ru:
  activerecord:
    attributes:
      project:
        title: Название
```

I'm expecting label on input field to be 'Title' for English tab and 'Название'  for Russian tab. Currently it shows 'Title' for both tabs.
Could you help me to solve the problem?

**Comment by stefanoverna** [comment]
I will try to investigate in the next few days :)

**Comment by mreq** [comment]
Any news on that? Should be an easy fix.

**Comment by stefanoverna** [comment]
Not a lot of time available right now. Patch welcome! :)

**Comment by mreq** [comment]
I was trying, to na avail. I'm not familiar with the insides of active_admin :( BTW Thanks for the gem, works great.

**Comment by tomeduarte** [comment]
@stefanoverna do you have any idea how to tackle this? I'm willing to give it a go if you can point me in the right direction.

At first glance, I'd say the culprit is [here](https://github.com/stefanoverna/activeadmin-globalize3/blob/master/lib/active_admin/globalize3/form_builder_extension.rb#L21), but I am lost as to why the form builder doesn't use the appropriate locale to build the labels.

Is this right, or am I looking at this totally wrong?

**Comment by stefanoverna** [comment]
Hey there, 0862d3863dee2f fixes this. You can specify to change locale for each tab using the `switch_locale` option.

**Comment by mreq** [comment]
Great work, thanks!

**Comment by tomeduarte** [comment]
Thank you for fixing that. I wasn't aware of `I18n.with_locale`, always learning! :smiley:

**Comment by marcusg** [comment]
@stefanoverna: thanks for that. But that fix only changes the translations for the tabs, not the text for the labels right?

**Comment by tomeduarte** [comment]
@marcusg I found my labels started to display correctly by adding them as formtastic labels.

Example:

``` yaml
"pt-PT":
  formtastic:
    labels:
      model_name:
        attribute_name: Exemplo
        another_attribute: Exemplo 2
```

Let me know if that helps :smile:.
